flask/notety/students/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, IntegerField, PasswordField, SelectField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError, Regexp
from flask_login import current_user
from notety.models import Student
from notety import students_collection




class RegistrationForm(FlaskForm):
    f_name = StringField('First name',
                           validators=[DataRequired(), Length(min=2, max=20)])
    
    l_name = StringField('Last name',
                           validators=[DataRequired(), Length(min=2, max=20)])
    

    class_name = SelectField('Select your class',
                           validators=[DataRequired()])

    cin = IntegerField('CIN',
                        validators=[DataRequired()])

    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                     validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        student= students_collection.find_one({"cin": self.cin.data})
        if student:
            raise ValidationError('That CIN is taken. Please choose a different one.')

    def validate_email(self, email):
        student= students_collection.find_one({"email": self.email.data})
        if student:
            raise ValidationError('That email is taken. Please choose a different one.')




class LoginForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

flask/notety/students/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from notety import db, bcrypt
from notety.models import Student
from notety import grades, students_collection, data_collection
from notety.students.forms import (RegistrationForm, LoginForm)
import datetime

students = Blueprint('students', __name__)

@students.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()

    fetched = data_collection.find({}).sort("class_name", 1)
    form.class_name.choices = [(None, 'Choose the class you belong to')]
    form.class_name.choices += [(_class["class_name"], _class["class_name"]) for _class in fetched]
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        student = {
            "f_name": form.f_name.data,
            "l_name": form.l_name.data,
            "class_name": form.class_name.data,
            "cin": form.cin.data,
            "email": form.email.data,
            "password": hashed_password,
            "inscription_date": datetime.datetime.now()
        }
        students_collection.insert_one(student)
        
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('students.login'))

    return render_template('students/register.html', title='Register', form=form)



@students.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user= students_collection.find_one({'email': form.email.data})
        if user and bcrypt.check_password_hash(user['password'], form.password.data):
                username = user['f_name'] + " " + user['l_name']
                email = user['email']
                cin = user['cin']
                
                user = Student(username, email, cin)
                login_user(user, remember=form.remember.data)

                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Please check email and password', 'danger')
    return render_template('students/login.html', title='Login', form=form)

@students.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('students.login'))


@students.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    return render_template('account.html', title='Account')




@students.route("/student/grades", methods=['GET', 'POST'])
@login_required
def get_result():
    grade = grades.find_one( {'student.cin': current_user.cin} )

    if grade is None:
        return render_template('students/grades.html', title='Consult Your Grades', results=False)
    
    sem1_modules = grade['sem1']
    sem2_modules = grade['sem2']


    return render_template('students/grades.html', title='Consult Your Grades', results=True, modules1=sem1_modules, modules2=sem2_modules)

flask/notety/templates/students/account.html
{% extends "common/layout.html" %}

{% if title %}
{% block title %} {{ title }} {% endblock title %}
{% endif %}

{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask/notety/templates/students/grades.html
{% extends "common/layout.html" %}
{% if title %}
{% block title %} {{ title }} {% endblock title %}
{% endif %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h5 class="card-title">Grades</h5>

        {% if results %}
        </br>
        </br>
        <h4>Results of 1st semester</h4>
        </br>
        <div class="container">
            <table class="table table-stripped">

                <thead>
                    <tr>
                        <th class="col-xs-2"> Module</th>
                        <th class="col-xs-2"> Subject</th>
                        <th class="col-xs-1"> Coefficient</th>
                        <th class="col-xs-2"> TP</th>
                        <th class="col-xs-2"> DS</th>
                        <th class="col-xs-1"> Exam</th>
                        <th class="col-xs-2"> Avg</th>
                    </tr>
                </thead>

                <tbody>
                    {% for module in modules1 %}
                    <tr>
                        <td class="col-xs-2" rowspan="{{ module['subjects']|length + 1 }}"> {{module['module_name']}}
                        </td>

                        {% for subject in module['subjects'] %}
                        <!-- TODO shouf kifèh tzid lforms-->

                    <tr>

                        <td class="col-xs-2">
                            {{ subject['subject'] }}

                        </td>

                        <td class="col-xs-1">
                            {{ subject['coef'] }}
                        </td>

                        {% if subject['tp'] %}

                        <td class="col-xs-1">{{ subject['tp'] }}</td>
                        {% else %}
                        <td class="col-xs-1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-x-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                            </svg>
                        </td>
                        {% endif %}


                        {% if subject['ds'] %}

                        <td class="col-xs-1">{{ subject['ds'] }}</td>
                        {% else %}
                        <td class="col-xs-1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-x-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                            </svg>
                        </td>
                        {% endif %}

                        {% if subject['exam'] %}

                        <td class="col-xs-1">{{ subject['exam'] }}</td>

                        {% else %}
                        <td class="col-xs-1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-x-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                            </svg>
                        </td>
                        {% endif %}


                        <td>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-peace" viewBox="0 0 16 16">
                                <path
                                    d="M7.5 1.018a7 7 0 0 0-4.79 11.566L7.5 7.793V1.018zm1 0v6.775l4.79 4.79A7 7 0 0 0 8.5 1.018zm4.084 12.273L8.5 9.207v5.775a6.97 6.97 0 0 0 4.084-1.691zM7.5 14.982V9.207l-4.084 4.084A6.97 6.97 0 0 0 7.5 14.982zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z" />
                            </svg>
                        </td>
                    </tr>



                    {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>



        </div>

        </br>
        </br>
        <h4>Results of 2nd semester</h4>
        </br>
        <div class="container">
            <table class="table table-stripped">

                <thead>
                    <tr>
                        <th class="col-xs-2"> Module</th>
                        <th class="col-xs-2"> Subject</th>
                        <th class="col-xs-1"> Coefficient</th>
                        <th class="col-xs-2"> TP</th>
                        <th class="col-xs-2"> DS</th>
                        <th class="col-xs-1"> Exam</th>
                        <th class="col-xs-2"> Avg</th>
                    </tr>
                </thead>



                <tbody>
                    {% for module in modules2 %}
                    <tr>
                        <td class="col-xs-2" rowspan="{{ module['subjects']|length + 1 }}"> {{module['module_name']}}
                        </td>

                        {% for subject in module['subjects'] %}
                        <!-- TODO shouf kifèh tzid lforms-->

                    <tr>

                        <td class="col-xs-2">
                            {{ subject['subject'] }}

                        </td>

                        <td class="col-xs-1">
                            {{ subject['coef'] }}
                        </td>

                        {% if subject['tp'] %}

                        <td class="col-xs-1">{{ subject['tp'] }}</td>
                        {% else %}
                        <td class="col-xs-1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-x-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                            </svg>
                        </td>
                        {% endif %}


                        {% if subject['ds'] %}

                        <td class="col-xs-1">{{ subject['ds'] }}</td>
                        {% else %}
                        <td class="col-xs-1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-x-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                            </svg>
                        </td>
                        {% endif %}

                        {% if subject['exam'] %}

                        <td class="col-xs-1">{{ subject['exam'] }}</td>

                        {% else %}
                        <td class="col-xs-1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-x-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path
                                    d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                            </svg>
                        </td>
                        {% endif %}


                        <td>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-peace" viewBox="0 0 16 16">
                                <path
                                    d="M7.5 1.018a7 7 0 0 0-4.79 11.566L7.5 7.793V1.018zm1 0v6.775l4.79 4.79A7 7 0 0 0 8.5 1.018zm4.084 12.273L8.5 9.207v5.775a6.97 6.97 0 0 0 4.084-1.691zM7.5 14.982V9.207l-4.084 4.084A6.97 6.97 0 0 0 7.5 14.982zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z" />
                            </svg>
                        </td>
                    </tr>



                    {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>



        </div>

        {% else %}
        <h1>You got no results yet !!</h1>

        {% endif %}

    </div>
</div>

<style>
    .table td {
        text-align: center;
    }

    .table th {
        text-align: center;
    }
</style>
{% endblock content %}

flask/notety/templates/students/login.html
<!DOCTYPE html>
<html>

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Notety - Login</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="shortcut icon" href="{{ url_for('static', filename='logo_transparent.png') }}">

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

    <style>
        body,
        html {
            height: 100%;
        }
    </style>
</head>



<body>
    <div class="d-flex align-items-center justify-content-center" style="height: 100%">
        <div class="container">
            <br>
            <div class="row">
                <aside class="col-sm-4">
                </aside>
                <aside class="col-sm-4">


                    <div class="card">
                        <article class="card-body">
                            <a href="{{ url_for('students.register') }}"
                                class="float-right btn btn-outline-primary">Sign up</a>
                            <h4 class="card-title mb-4 mt-1">Sign in</h4>
                            <p>
                                <a href="#" class="btn btn-block btn-outline-info"> <i class="fab fa-twitter"></i>
                                    &nbsp;
                                    Login
                                    via Twitter</a>
                                <a href="#" class="btn btn-block btn-outline-primary"> <i class="fab fa-facebook-f"></i>
                                    &nbsp;
                                    Login via facebook</a>
                            </p>
                            <hr>
                            <form method="POST" action="">
                                {{ form.hidden_tag() }}
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                                        </div>
                                        {% if form.email.errors %}
                                        {{ form.email(class="form-control is-invalid", placeholder="Email") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.email.errors %}
                                            <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.email(class="form-control", placeholder="Email") }}
                                        {% endif %}
                                    </div> <!-- input-group.// -->
                                </div> <!-- form-group// -->
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                        </div>
                                        {% if form.password.errors %}
                                        {{ form.password(class="form-control is-invalid", placeholder="********") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.password.errors %}
                                            <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                        {% else %}
                                        {{ form.password(class="form-control", placeholder="********") }}
                                        {% endif %}
                                    </div> <!-- input-group.// -->
                                </div> <!-- form-group// -->
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="form-check">
                                            {{ form.remember(class="form-check-input") }}
                                            {{ form.remember.label(class="form-check-label") }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            {{ form.submit(class="btn btn-outline-primary") }}
                                        </div> <!-- form-group// -->
                                    </div>
                                    <div class="col-md-6 text-right">
                                        <a class="small" href="#">Forgot password?</a></br>
                                        <a class="small text-success" href="{{ url_for('admin.login') }}">Log in as Admin</a> 
                                    </div>
                                </div> <!-- .row// -->
                            </form>
                            
                        </article>
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-12">
                                    {% with messages = get_flashed_messages(with_categories=true) %}
                                    {% if messages %}
                                    {% for category, message in messages %}
                                    <div class="alert alert-{{ category }}">
                                        {{ message }}
                                    </div>
                                    {% endfor %}
                                    {% endif %}
                                    {% endwith %}
    
                                </div>
                            </div>
                        </div>
                    </div> <!-- card.// -->

                </aside> <!-- col.// -->
            </div> <!-- row.// -->

        </div>
        <!--container end.//-->
    </div>

    <br><br><br>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>



</body>

</html>

flask/notety/templates/students/student-dashboard.html
<!--
<div class="container">
  <div class="card border-success mb-3" style="max-width: 18rem;">
    <div class="card-header">Activity</div>
    <div class="card-body text-success">
      <h5 class="card-title">Success card title</h5>
      <p class="card-text">As a student you can get your results during the year through this link</p>
      <a href="{{ url_for('students.get_result') }}" class="btn btn-outline-success">SEE RESULTS</a>
    </div>
  </div>
</div>

-->
<div class="container">
  <div class="row">
    <div class="col-4"></div>
    <div class="col-4">

      <div class="card text-center d-flex justify-content-center">
        <div class="card-header bg-transparent border-info">Grades consultation</div>
        <div class="card-body text-info">
          <p class="card-text">You can get your results during the year through this link</p>
        </div>
        <div class="card-footer bg-transparent border-info d-flex justify-content-center">
          <a class="btn btn-outline-info" href="{{ url_for('students.get_result') }}">SEE RESULTS</a>
        </div>

      </div>
    </div>
  </div>
</div>